import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlarmClock, Bell, Check, ChevronDown, ChevronUp, Circle, Clock3, GripVertical, ListTodo, Plus, Trash2, X } from 'lucide-react';
import './style.css';

const API = `${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api`;
const pad = n => String(n).padStart(2, '0');
function App() {
  const [tasks, setTasks] = useState([]), [text, setText] = useState(''), [filter, setFilter] = useState('all');
  const [remindTask, setRemindTask] = useState(null), [remindValue, setRemindValue] = useState(''), [duration, setDuration] = useState('');
  const [now, setNow] = useState(Date.now()), [error, setError] = useState('');
  const load = async () => { try { const r = await fetch(`${API}/tasks`); if (!r.ok) throw Error(); setTasks(await r.json()); setError(''); } catch { setError('Could not reach the app server. Start it with start.ps1.'); } };
  useEffect(() => { load(); const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []);
  useEffect(() => { tasks.forEach(t => { if (!t.done && t.reminder && new Date(t.reminder).getTime() <= now && !sessionStorage.getItem(`reminded-${t.id}-${t.reminder}`)) { sessionStorage.setItem(`reminded-${t.id}-${t.reminder}`, 'yes'); if ('Notification' in window && Notification.permission === 'granted') new Notification('Little List reminder', { body: t.title }); } }); }, [now, tasks]);
  const save = async (id, data) => { const r = await fetch(`${API}/tasks/${id}`, { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify(data) }); if (!r.ok) setError('Could not save that change.'); else load(); };
  const add = async e => { e.preventDefault(); if (!text.trim()) return; const r = await fetch(`${API}/tasks`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({title:text.trim()}) }); if (r.ok) { setText(''); load(); } else setError('Could not add your task.'); };
  const remove = async id => { await fetch(`${API}/tasks/${id}`, {method:'DELETE'}); load(); };
  const sorted = useMemo(() => tasks.filter(t => filter === 'all' || (filter === 'active' ? !t.done : t.done)), [tasks, filter]);
  const move = (i, d) => { const other = sorted[i+d]; if (!other) return; Promise.all([save(sorted[i].id, {position: other.position}), save(other.id, {position: sorted[i].position})]); };
  const openReminder = t => { setRemindTask(t); setRemindValue(t.reminder ? new Date(new Date(t.reminder).getTime()-new Date(t.reminder).getTimezoneOffset()*60000).toISOString().slice(0,16) : ''); setDuration(''); };
  const setReminder = async e => { e.preventDefault(); if (remindValue && 'Notification' in window && Notification.permission === 'default') await Notification.requestPermission(); await save(remindTask.id, { reminder: remindValue ? new Date(remindValue).toISOString() : null }); setRemindTask(null); };
  const setTimer = async () => { const mins = Number(duration); if (!mins || mins < 1) return; await save(remindTask.id, {timer_end:new Date(Date.now()+mins*60000).toISOString()}); setRemindTask(null); };
  const active = tasks.filter(t => !t.done).length;
  return <main className="page"><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><ListTodo size={19}/></span> little list</a><span className="top-note">A little more room to think.</span></header>
    <section className="intro"><div className="eyebrow"><span className="sparkle">✳</span> YOUR PERSONAL SPACE</div><h1>Make today<br/><em>feel lighter.</em></h1><p>A quiet place to gather your thoughts and take things one at a time.</p></section>
    <section className="board"><div className="board-head"><div><div className="date">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div><h2>Your list <span className="count">{active}</span></h2></div><div className="filter">{[['all','All'],['active','To do'],['done','Done']].map(([key,label])=><button key={key} className={filter===key?'selected':''} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>
    <form className="add-form" onSubmit={add}><Plus size={19}/><input value={text} onChange={e=>setText(e.target.value)} placeholder="What would you like to get done?" aria-label="New task"/><button type="submit" disabled={!text.trim()}>Add task <span>↵</span></button></form>
    {error&&<div className="error">{error}</div>}
    {sorted.length ? <div className="tasks">{sorted.map((t,i)=><article className={`task ${t.done?'is-done':''}`} key={t.id}><button className="check" aria-label={t.done?'Mark incomplete':'Mark complete'} onClick={()=>save(t.id,{done:!t.done})}>{t.done?<Check size={15}/>:<Circle size={21}/>}</button><div className="task-main"><div className="task-title">{t.title}</div><div className="meta">{t.reminder&&<span className="meta-pill"><Bell size={12}/>{new Date(t.reminder).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span>}{t.timer_end&&<span className="meta-pill timer"><Clock3 size={12}/>{Math.max(0,Math.ceil((new Date(t.timer_end).getTime()-now)/1000/60))}m left</span>}</div></div><div className="actions"><button title="Set reminder or timer" aria-label="Set reminder or timer" onClick={()=>openReminder(t)}><AlarmClock size={17}/></button><button title="Move up" aria-label="Move up" onClick={()=>move(i,-1)} disabled={i===0}><ChevronUp size={17}/></button><button title="Move down" aria-label="Move down" onClick={()=>move(i,1)} disabled={i===sorted.length-1}><ChevronDown size={17}/></button><button title="Delete task" aria-label="Delete task" className="delete" onClick={()=>remove(t.id)}><Trash2 size={16}/></button></div></article>)}</div>:<div className="empty"><div className="empty-icon">{filter==='done'?'✓':'✳'}</div><strong>{filter==='done'?'Nothing checked off yet.':filter==='active'?'You’re all caught up.':'A fresh page.'}</strong><span>{filter==='all'?'Add a task above and give it a home.':'Your list is looking clear.'}</span></div>}
    <footer className="board-foot"><span><GripVertical size={14}/> Take it one thing at a time</span><span>{tasks.length-active} completed</span></footer></section>
    <footer className="page-foot">A softer way to get things done <span>✳</span></footer>
    {remindTask&&<div className="overlay" onClick={()=>setRemindTask(null)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">MAKE A LITTLE PLAN</div><h3>{remindTask.title}</h3></div><button className="close" onClick={()=>setRemindTask(null)}><X size={18}/></button></div><form onSubmit={setReminder}><label htmlFor="reminder">Remind me at</label><input id="reminder" type="datetime-local" value={remindValue} onChange={e=>setRemindValue(e.target.value)}/><div className="modal-buttons"><button type="button" className="text-button" onClick={()=>save(remindTask.id,{reminder:null}).then(()=>setRemindTask(null))}>Clear reminder</button><button className="primary">Save reminder</button></div></form><div className="divider"><span>OR SET A TIMER</span></div><div className="timer-row"><input aria-label="Timer duration in minutes" type="number" min="1" max="1440" placeholder="25" value={duration} onChange={e=>setDuration(e.target.value)}/><span>minutes</span><button className="primary" onClick={setTimer}>Start timer</button></div><p className="modal-note">Browser notifications appear while this page is open. Allow notifications when prompted.</p></section></div>}
  </main>;
}

createRoot(document.getElementById('root')).render(<App/>);
